//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YoutubeViewer.Modules.YoutubeContent.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YoutubeViewer.Modules.YoutubeContent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   チャンネルの追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddChannelButtonTooltip {
            get {
                return ResourceManager.GetString("AddChannelButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   下へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DownChannelButtonTooltip {
            get {
                return ResourceManager.GetString("DownChannelButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェンネルの編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditChannelButtonTooltip {
            get {
                return ResourceManager.GetString("EditChannelButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャンネルの削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RemoveChannelButtonTooltip {
            get {
                return ResourceManager.GetString("RemoveChannelButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上へ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpChannelButtonTooltip {
            get {
                return ResourceManager.GetString("UpChannelButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻る (Alt + Left) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebViewPageBackButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageBackButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページの読み込みに失敗しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebViewPageFaildedMessage {
            get {
                return ResourceManager.GetString("WebViewPageFaildedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   進む (Alt + Right) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebViewPageForwardButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageForwardButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebViewPageLoadingText {
            get {
                return ResourceManager.GetString("WebViewPageLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブラウザを開く (Ctrl + T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebViewPageOpenInBrowserButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageOpenInBrowserButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新(F5) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WebViewPageRefreshButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageRefreshButtonTooltip", resourceCulture);
            }
        }
    }
}
